services:  
  backend:
    container_name: "Engine"
    build:
      context: ./Engine
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
  
  frontend:
    container_name: "Frontend"
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
